[tool.poetry]
name = "hasher"
version = "2.0.1"
description = "Provide multiple hashing algorithms from a single code base"
license = "Apache-2.0"
authors = ["Walter Scheper <walter.scheper@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/wfscheper/hasher"
repository = "https://github.com/wfscheper/hasher.git"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Utilities",
]

[tool.poetry.scripts]
hasher = "hasher.app:hasher"

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
click = "^7.0"

[tool.poetry.dev-dependencies]
black = {version = "*",allows-prereleases = true,python = ">=3.6"}
pytest = "^4.3"
pytest-mock = "^1.10"
isort = {version = "^4.3",extras = ["pyproject"]}
flake8 = "^3.7"
pytest-cov = "^2.6"
more-itertools = {version = "^5.0",python = "^2.7"}

[tool.black]
line-length = 132

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 132

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
