[tool.poetry]
name = "hasher"
version = "2.0.1"
description = "Provide multiple hashing algorithms from a single code base"
authors = ["Walter Scheper <walter.scheper@gmail.com>"]
license = "Apache-2.0"
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Environment :: Console",
	"Intended Audience :: Developers",
	"Intended Audience :: Information Technology",
	"Intended Audience :: System Administrators",
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: OS Independent",
	"Programming Language :: Python",
	"Topic :: Utilities",
]

[tool.poetry.scripts]
hasher = "hasher.main:main"

[tool.poetry.plugins]
[tool.poetry.plugins.hasher]
md5 = "hasher.hashes:MD5Hasher"
sha1 = "hasher.hashes:SHA1Hasher"
sha256 = "hasher.hashes:SHA256Hasher"

[tool.poetry.dependencies]
python = "^2.7"
cliff = "^1.4"
argparse = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "*"
mock = "^2.0"
more-itertools = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
