# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: hasher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    name: py${{ matrix.python-version}}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Bootstrap poetry
      run: pipx install poetry

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true

    - name: Check lock file
      run: poetry check --lock

    - name: Install dependencies
      run: poetry install --with github-actions

    - name: Run linters
      run: make lint

    - name: Run tests
      run: make test
